In [26]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use('fivethirtyeight')

In [1]:
#!pip install joblib

In [51]:
class Percptron:
    def __init__(self,eta: float=None,epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta  # Learning Rate
        self.epochs= epochs # Iteration
    def _z_outcome(self, inputs,weights):
        return np.dot(inputs,weights)
    
    def activation_function(self,z):
        return np.where(z>0,1,0)
    
    def fit(self,X,y):
        self.X= X
        self.y = y
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with Bias:\n {X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch  >> {epoch+1}")
            
            z = self._z_outcome(X_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value :\n {y_hat}")
            self.error = self.y-y_hat
            print(f"error value :\n {self.error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
            print(f"updated weight value after epoch:{epoch} :\n {self.weights}")
            print("##"*10)

    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)

In [52]:
OR = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,1]
}

df_OR = pd.DataFrame(OR)

In [57]:
AND = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,0,0,1]
}

df_AND = pd.DataFrame(AND)

In [58]:
XOR = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)

In [59]:
def prepare_data(df, target_col= 'y'):
    X = df.drop(target_col,axis = 1)
    y = df[target_col]
    return X,y

In [60]:
X,y = prepare_data(df_OR)
eta = 0.1
EPOCHS = 10
model_or = Percptron(eta=eta,epochs=EPOCHS)
model_or.fit(X,y)

X with Bias:
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch  >> 1
predicted value :
 [1 1 0 1]
error value :
 0   -1
1    0
2    1
3    0
Name: y, dtype: int64
updated weight value after epoch:0 :
 [ 9.99435666e-02  1.19500358e-04 -3.66815853e-05]
####################
--------------------
for epoch  >> 2
predicted value :
 [1 1 1 1]
error value :
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weight value after epoch:1 :
 [0.09994357 0.0001195  0.09996332]
####################
--------------------
for epoch  >> 3
predicted value :
 [0 0 0 1]
error value :
 0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weight value after epoch:2 :
 [ 0.19994357  0.1001195  -0.10003668]
####################
--------------------
for epoch  >> 4
predicted value :
 [1 1 1 1]
error value :
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weight value after epoch:3 :
 [ 1.99943567e-01  1.00119500e-01 -3.66815853e-05]
#############

In [61]:
X,y = prepare_data(df_AND)
eta = 0.1
EPOCHS = 10
model_or = Percptron(eta=eta,epochs=EPOCHS)
model_or.fit(X,y)

X with Bias:
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch  >> 1
predicted value :
 [1 1 1 1]
error value :
 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weight value after epoch:0 :
 [-0.09999163 -0.10000584  0.2999738 ]
####################
--------------------
for epoch  >> 2
predicted value :
 [0 0 0 0]
error value :
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weight value after epoch:1 :
 [ 8.36894697e-06 -5.83757796e-06  1.99973796e-01]
####################
--------------------
for epoch  >> 3
predicted value :
 [0 0 0 0]
error value :
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weight value after epoch:2 :
 [0.10000837 0.09999416 0.0999738 ]
####################
--------------------
for epoch  >> 4
predicted value :
 [0 1 1 1]
error value :
 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weight value after epoch:3 :
 [ 8.36894697e-06 -5.83757796e-06  2.99973796e-01]
#############

In [62]:
X,y = prepare_data(df_XOR)
eta = 0.1
EPOCHS = 10
model_or = Percptron(eta=eta,epochs=EPOCHS)
model_or.fit(X,y)

X with Bias:
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch  >> 1
predicted value :
 [0 0 1 0]
error value :
 0    0
1    1
2    0
3    0
Name: y, dtype: int64
updated weight value after epoch:0 :
 [ 0.0001661   0.09985049 -0.09989852]
####################
--------------------
for epoch  >> 2
predicted value :
 [1 1 1 1]
error value :
 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weight value after epoch:1 :
 [-0.0998339  -0.00014951  0.10010148]
####################
--------------------
for epoch  >> 3
predicted value :
 [0 0 0 0]
error value :
 0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weight value after epoch:2 :
 [ 0.0001661   0.09985049 -0.09989852]
####################
--------------------
for epoch  >> 4
predicted value :
 [1 1 1 1]
error value :
 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weight value after epoch:3 :
 [-0.0998339  -0.00014951  0.10010148]
####################
-------------

In [49]:
model_or.predict(X=[[0,0]])

array([0])

In [21]:
obj = Percptron(eta= 0.01,epochs=10)
obj.eta

0.01

In [22]:
obj.epochs

10

In [23]:
obj.weights

array([-8.67594466e-05, -6.67546787e-05, -1.46447598e-05])

In [7]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
y = np.ones((4, 1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [25]:
obj.fit(X, y)

X with Bias:
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [12]:
np.c_[X, -np.ones((len(X),1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])